/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SssRouteImport } from './routes/sss'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SifreYenileRouteImport } from './routes/sifre-yenile'
import { Route as SifreSifirlaRouteImport } from './routes/sifre-sifirla'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PaketlerRouteImport } from './routes/paketler'
import { Route as KayitRouteImport } from './routes/kayit'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as GorsellerRouteImport } from './routes/gorseller'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiReportRouteImport } from './routes/api/report'
import { Route as ApiAnalyseRouteImport } from './routes/api/analyse'

const SssRoute = SssRouteImport.update({
  id: '/sss',
  path: '/sss',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SifreYenileRoute = SifreYenileRouteImport.update({
  id: '/sifre-yenile',
  path: '/sifre-yenile',
  getParentRoute: () => rootRouteImport,
} as any)
const SifreSifirlaRoute = SifreSifirlaRouteImport.update({
  id: '/sifre-sifirla',
  path: '/sifre-sifirla',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketlerRoute = PaketlerRouteImport.update({
  id: '/paketler',
  path: '/paketler',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitRoute = KayitRouteImport.update({
  id: '/kayit',
  path: '/kayit',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const GorsellerRoute = GorsellerRouteImport.update({
  id: '/gorseller',
  path: '/gorseller',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportRoute = ApiReportRouteImport.update({
  id: '/api/report',
  path: '/api/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyseRoute = ApiAnalyseRouteImport.update({
  id: '/api/analyse',
  path: '/api/analyse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/gorseller': typeof GorsellerRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kayit': typeof KayitRoute
  '/paketler': typeof PaketlerRoute
  '/panel': typeof PanelRoute
  '/profil': typeof ProfilRoute
  '/sifre-sifirla': typeof SifreSifirlaRoute
  '/sifre-yenile': typeof SifreYenileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
  '/api/analyse': typeof ApiAnalyseRoute
  '/api/report': typeof ApiReportRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/gorseller': typeof GorsellerRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kayit': typeof KayitRoute
  '/paketler': typeof PaketlerRoute
  '/panel': typeof PanelRoute
  '/profil': typeof ProfilRoute
  '/sifre-sifirla': typeof SifreSifirlaRoute
  '/sifre-yenile': typeof SifreYenileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
  '/api/analyse': typeof ApiAnalyseRoute
  '/api/report': typeof ApiReportRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/gorseller': typeof GorsellerRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kayit': typeof KayitRoute
  '/paketler': typeof PaketlerRoute
  '/panel': typeof PanelRoute
  '/profil': typeof ProfilRoute
  '/sifre-sifirla': typeof SifreSifirlaRoute
  '/sifre-yenile': typeof SifreYenileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
  '/api/analyse': typeof ApiAnalyseRoute
  '/api/report': typeof ApiReportRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/giris'
    | '/gorseller'
    | '/hakkimizda'
    | '/iletisim'
    | '/kayit'
    | '/paketler'
    | '/panel'
    | '/profil'
    | '/sifre-sifirla'
    | '/sifre-yenile'
    | '/sitemap.xml'
    | '/sss'
    | '/api/analyse'
    | '/api/report'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/giris'
    | '/gorseller'
    | '/hakkimizda'
    | '/iletisim'
    | '/kayit'
    | '/paketler'
    | '/panel'
    | '/profil'
    | '/sifre-sifirla'
    | '/sifre-yenile'
    | '/sitemap.xml'
    | '/sss'
    | '/api/analyse'
    | '/api/report'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/giris'
    | '/gorseller'
    | '/hakkimizda'
    | '/iletisim'
    | '/kayit'
    | '/paketler'
    | '/panel'
    | '/profil'
    | '/sifre-sifirla'
    | '/sifre-yenile'
    | '/sitemap.xml'
    | '/sss'
    | '/api/analyse'
    | '/api/report'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GirisRoute: typeof GirisRoute
  GorsellerRoute: typeof GorsellerRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  KayitRoute: typeof KayitRoute
  PaketlerRoute: typeof PaketlerRoute
  PanelRoute: typeof PanelRoute
  ProfilRoute: typeof ProfilRoute
  SifreSifirlaRoute: typeof SifreSifirlaRoute
  SifreYenileRoute: typeof SifreYenileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SssRoute: typeof SssRoute
  ApiAnalyseRoute: typeof ApiAnalyseRoute
  ApiReportRoute: typeof ApiReportRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sss': {
      id: '/sss'
      path: '/sss'
      fullPath: '/sss'
      preLoaderRoute: typeof SssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sifre-yenile': {
      id: '/sifre-yenile'
      path: '/sifre-yenile'
      fullPath: '/sifre-yenile'
      preLoaderRoute: typeof SifreYenileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sifre-sifirla': {
      id: '/sifre-sifirla'
      path: '/sifre-sifirla'
      fullPath: '/sifre-sifirla'
      preLoaderRoute: typeof SifreSifirlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paketler': {
      id: '/paketler'
      path: '/paketler'
      fullPath: '/paketler'
      preLoaderRoute: typeof PaketlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit': {
      id: '/kayit'
      path: '/kayit'
      fullPath: '/kayit'
      preLoaderRoute: typeof KayitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gorseller': {
      id: '/gorseller'
      path: '/gorseller'
      fullPath: '/gorseller'
      preLoaderRoute: typeof GorsellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report': {
      id: '/api/report'
      path: '/api/report'
      fullPath: '/api/report'
      preLoaderRoute: typeof ApiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyse': {
      id: '/api/analyse'
      path: '/api/analyse'
      fullPath: '/api/analyse'
      preLoaderRoute: typeof ApiAnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GirisRoute: GirisRoute,
  GorsellerRoute: GorsellerRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  KayitRoute: KayitRoute,
  PaketlerRoute: PaketlerRoute,
  PanelRoute: PanelRoute,
  ProfilRoute: ProfilRoute,
  SifreSifirlaRoute: SifreSifirlaRoute,
  SifreYenileRoute: SifreYenileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SssRoute: SssRoute,
  ApiAnalyseRoute: ApiAnalyseRoute,
  ApiReportRoute: ApiReportRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
